[pytest]
# --video on: minden tesztről készül videó
# --screenshot on: minden tesztről készül kép
# --allure-no-capture: megakadályozza, hogy az Allure elrejtse a logokat/mellékleteket
addopts = --alluredir=allure-results --video on --screenshot on --allure-no-capture

python_files = test_*.py
testpaths = tests
markers =
    ui: Felhasználói felület tesztek
    api: API tesztek
