[pytest]
# Csak az alapokat hagyjuk meg, a videót a conftest.py kezeli kézzel
addopts = --alluredir=allure-results --screenshot on --allure-no-capture

python_files = test_*.py
testpaths = tests
markers =
    ui: UI tesztek
    api: API tesztek
    database: Custom marker for database integration tests

