[pytest]

# Alapértelmezett kapcsolók a futtatáshoz:
# --alluredir: hova mentse a nyers riport adatokat
# --video on: minden tesztről készüljön videó (használhatod a 'retain-on-failure' opciót is, ha csak a hibásakról kérsz)
# --screenshot on: minden teszt végén készüljön kép
addopts = --alluredir=allure-results --video on --screenshot on

# Teszt fájlok keresési mintája
python_files = test_*.py

# Teszt könyvtárak meghatározása
testpaths = tests

# Egyedi markerek regisztrálása (opcionális, pl. @pytest.mark.api)
markers =
    ui: UI szintű tesztek
    api: API szintű tesztek
    smoke: Kritikus tesztek gyűjteménye
