name: Playwright Tests with Allure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Válaszd ki a futtatandó tesztcsomagot (HR indítás):'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - login
          - database
          - file_management

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      - name: Ensure Playwright browsers are installed
        run: playwright install --with-deps chromium

      - name: Run tests
        run: |
          mkdir -p videos
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.test_suite }}" != "all" ]; then
            if [ "${{ github.event.inputs.test_suite }}" == "login" ]; then
              python -m pytest tests/UI/test_login.py --alluredir=allure-results
            elif [ "${{ github.event.inputs.test_suite }}" == "database" ]; then
              python -m pytest -m database --alluredir=allure-results
            elif [ "${{ github.event.inputs.test_suite }}" == "file_management" ]; then
              python -m pytest tests/test_integration.py tests/test_excel_e2e.py --alluredir=allure-results
            fi
          else
            python -m pytest tests --alluredir=allure-results
          fi

      - name: Get Allure history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from github-actions-automation
        if: always()
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
